# Generated by Django 4.2.16 on 2024-09-22 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPYTK', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
